name:  Teacher Web Automation CI

on:
  pull_request:
    branches: ["dev"]   # PR → smoke tests
  push:
    branches: ["main","dev"]  # main → regression
  schedule:
    - cron: '0 2 * * *'  # nightly run

jobs:
  # ===================== SMOKE TEST JOB =====================
  smoke-tests:
    name: Smoke Tests
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    env:
      TEACHER_WEB: https://teacher.englishgurukul.in/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        shell: powershell
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Smoke Tests
        shell: powershell
        run: |
          pytest -m smoke -v -s --alluredir=allure-results

      - name: Install Allure CLI
        shell: powershell
        run: |
          npm install -g allure-commandline

      - name: Generate Allure Report
        shell: powershell
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-allure-report
          path: allure-report

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-screenshots
          path: screenshots/


  # ================= GITHUB PAGES =================
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy Report
        uses: actions/deploy-pages@v4


  # ===================== REGRESSION TEST JOB =====================
  regression-tests:
    name: Regression Tests
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    env:
      TEACHER_WEB: https://teacher.englishgurukul.in/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        shell: powershell
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Regression Tests
        shell: powershell
        run: |
          pytest -m regression -v -s --alluredir=allure-results

      - name: Install Allure CLI
        shell: powershell
        run: |
          npm install -g allure-commandline

      - name: Generate Allure Report
        shell: powershell
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: regression-allure-report
          path: allure-report

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: regression-screenshots
          path: screenshots/
